export type Labels = typeof zhCN;

const zhCN = {
  ready: "就绪",
  subtitle: "桌面 OCR 翻译工作台",
  home: "首页",
  history: "历史记录",
  settings: "设置",
  workspaceTitle: "翻译工作台",
  textInput: "输入文本",
  textInputPlaceholder: "输入、粘贴文本，或从截图/图片选区 OCR 后自动填入。",
  translateText: "翻译文本",
  startOverlay: "开始框选截图",
  captureRegion: "截取区域",
  imageInput: "图片输入",
  selectImage: "选择图片",
  regionFields: "区域 X/Y/宽/高",
  resultMetadata: "结果信息",
  ocrRegion: "识别选区",
  ocrAndTranslate: "识别并翻译",
  translateRegion: "翻译区域",
  retranslate: "重新翻译",
  copy: "复制",
  playSource: "播放原文",
  playTranslation: "播放译文",
  stopSpeech: "停止朗读",
  noSpeechText: "没有可播放的文本",
  speechDisabled: "语音朗读未启用",
  speechEnableToPlay: "启用语音朗读后才能播放",
  speechUnsupported: "当前环境不支持系统朗读",
  speechStarted: "正在朗读",
  pin: "固钉",
  unpin: "取消固钉",
  close: "关闭",
  translationPlaceholder: "翻译结果会显示在这里。",
  sourcePlaceholder: "OCR 或划词原文会显示在这里。",
  noImageSelected: "未选择图片",
  imageLoaded: "图片已加载",
  textInputRequired: "请输入要翻译的文本",
  textTranslated: "文本已翻译",
  selectionTextExtracted: "划词文本已提取",
  ocrTextExtracted: "OCR 文本已提取",
  imageTranslated: "图片已翻译",
  regionTranslated: "区域已翻译",
  selectedRegionTooSmall: "选区太小",
  noImageDimensions: "图片尺寸尚未就绪，请重新选择图片后再框选。",
  unsupportedImageType: "不支持的图片类型，请使用 PNG、JPEG 或 WebP。",
  noResultToCopy: "没有可复制的结果",
  resultCopied: "已复制",
  resultPinned: "已固钉",
  resultUnpinned: "已取消固钉",
  resultClosed: "结果已关闭",
  backHome: "返回主页",
  loadingSettings: "正在加载设置...",
  settingsInterface: "界面",
  settingsHotkeys: "快捷键",
  interfaceLanguage: "显示语言",
  languageChinese: "中文",
  languageEnglish: "English",
  targetLanguage: "目标语言",
  theme: "主题",
  themeSystemDescription: "勾选后，SnapText 将跟随设备的系统设置切换主题模式",
  resultDock: "结果停靠",
  screenshotHotkey: "截图热键",
  selectionHotkey: "划词热键",
  hotkeyInputPlaceholder: "按下快捷键",
  validateModels: "检查 OCR 模型",
  save: "保存",
  saving: "保存中",
  saved: "已保存",
  saveSettings: "保存配置",
  saveSettingsHint: "保存后会立即更新运行中的配置，新翻译请求会使用最新设置。",
  speech: "语音",
  speechEnabled: "启用语音朗读",
  englishAccent: "英语发音",
  englishAccentAmerican: "美式发音",
  englishAccentBritish: "英式发音",
  speechRate: "语速",
  speechVolume: "音量",
  speechSystem: "系统朗读",
  provider: "翻译服务",
  snaptextCloudProvider: "SnapText 官方源",
  providerSaveHint:
    "切换翻译源后会自动保存，新翻译请求会使用最新设置。",
  unsavedChanges: "有未保存更改",
  refresh: "刷新",
  clear: "清空",
  clearWorkspaceText: "清空原文和译文",
  workspaceTextCleared: "原文和译文已清空",
  copyHistory: "复制历史",
  open: "打开",
  cancel: "取消",
  pinnedResult: "固钉结果",
  pinnedResultWindow: "固钉结果窗口",
  sourceType: "来源类型",
  sourceText: "原文",
  translationText: "译文",
  noResult: "暂无结果",
  noTarget: "暂无目标语言",
  sourceScreenshot: "截图",
  sourceSelection: "划词",
  sourceImage: "图片",
  sourceTextKind: "文本",
  preparingOverlay: "正在准备框选窗口",
  overlayInstruction: "拖拽选择区域，松开后翻译，按 Escape 取消。",
  noOverlayScreenshot: "暂无可用的框选截图",
  ocrSelectedRegion: "正在识别所选区域",
  translatingSelectedRegion: "正在翻译所选区域",
  translating: "正在翻译",
  overlayClosed: "框选窗口已关闭",
  modelStatusNotChecked: "尚未检查 OCR 模型",
  configurationNotValidated: "配置尚未校验",
  configSaved: "配置已保存",
  ocrModelsValidated: "OCR 模型可用",
  ocrModelFilesMissing: "OCR 模型不可用",
  historyLoaded: "历史记录已加载",
  historyCleared: "历史记录已清空",
  noHistoryTitle: "暂无历史记录",
  noHistoryDescription: "完成一次文本、截图或图片翻译后，记录会显示在这里。",
  noHistoryToCopy: "没有可复制的历史记录",
  historyCopied: "历史记录已复制",
  historyItemOpened: "已打开历史记录",
  pinnedWindowHidden: "固钉窗口已隐藏",
  noSourceTextForRetranslation: "没有可重新翻译的原文",
  resultRetranslated: "结果已重新翻译",
  autoDetectLanguage: "自动识别",
  themeSystem: "跟随系统",
  themeLight: "浅色",
  themeDark: "深色",
  dockCursor: "跟随光标",
  dockFixed: "固定面板",
};

const en: Labels = {
  ...zhCN,
  ready: "Ready",
  subtitle: "Desktop OCR translation workspace",
  home: "Home",
  history: "History",
  settings: "Settings",
  workspaceTitle: "Translation workspace",
  textInput: "Text input",
  textInputPlaceholder:
    "Type or paste text, or fill it from a screenshot/image OCR region.",
  translateText: "Translate text",
  startOverlay: "Select screenshot area",
  captureRegion: "Capture region",
  imageInput: "Image input",
  selectImage: "Select image",
  regionFields: "Region X/Y/W/H",
  resultMetadata: "Result metadata",
  ocrRegion: "OCR region",
  ocrAndTranslate: "OCR and translate",
  translateRegion: "Translate region",
  retranslate: "Retranslate",
  copy: "Copy",
  playSource: "Play source",
  playTranslation: "Play translation",
  stopSpeech: "Stop speech",
  noSpeechText: "No text to play",
  speechDisabled: "Speech is disabled",
  speechEnableToPlay: "Enable speech to play audio",
  speechUnsupported: "System speech is not available",
  speechStarted: "Speaking",
  pin: "Pin",
  unpin: "Unpin",
  close: "Close",
  translationPlaceholder: "Translation result will appear here.",
  sourcePlaceholder: "OCR or selected source text will appear here.",
  noImageSelected: "No image selected",
  imageLoaded: "Image loaded",
  textInputRequired: "Enter text to translate",
  textTranslated: "Text translated",
  selectionTextExtracted: "Selected text extracted",
  ocrSelectedRegion: "Recognizing selected area",
  translatingSelectedRegion: "Translating selected area",
  translating: "Translating",
  autoDetectLanguage: "Auto-detect",
  sourceType: "Source type",
  sourceText: "Source",
  translationText: "Translation",
  backHome: "Back home",
  loadingSettings: "Loading settings...",
  settingsInterface: "Interface",
  settingsHotkeys: "Hotkeys",
  interfaceLanguage: "Display language",
  languageChinese: "Chinese",
  languageEnglish: "English",
  targetLanguage: "Target language",
  theme: "Theme",
  themeSystem: "Follow system",
  themeSystemDescription: "When enabled, SnapText follows the device system appearance setting.",
  themeLight: "Light",
  themeDark: "Dark",
  screenshotHotkey: "Screenshot hotkey",
  selectionHotkey: "Selection hotkey",
  hotkeyInputPlaceholder: "Press shortcut",
  saving: "Saving",
  saved: "Saved",
  saveSettings: "Save settings",
  saveSettingsHint:
    "Saving updates the running configuration for new translation requests.",
  clearWorkspaceText: "Clear source and translation",
  workspaceTextCleared: "Source and translation cleared",
  speech: "Speech",
  speechEnabled: "Enable speech",
  englishAccent: "English accent",
  englishAccentAmerican: "American",
  englishAccentBritish: "British",
  speechRate: "Rate",
  speechVolume: "Volume",
  speechSystem: "System speech",
  provider: "Translation service",
  snaptextCloudProvider: "SnapText Cloud",
  providerSaveHint:
    "Provider changes are saved automatically for new translation requests.",
  unsavedChanges: "Unsaved changes",
  noHistoryTitle: "No history yet",
  noHistoryDescription:
    "Text, screenshot, and image translations will appear here after you run them.",
};

export function labelsForLanguage(language?: string): Labels {
  return language === "en" ? en : zhCN;
}
