export type Labels = typeof zhCN;

const zhCN = {
  ready: "就绪",
  subtitle: "桌面 OCR 翻译工作台",
  home: "首页",
  history: "历史记录",
  settings: "设置",
  workspaceTitle: "翻译工作台",
  textInput: "输入文本",
  textInputPlaceholder: "输入、粘贴文本，或从截图/图片选区 OCR 后自动填入。",
  translateText: "翻译文本",
  startOverlay: "开始框选截图",
  captureRegion: "截取区域",
  imageInput: "图片输入",
  selectImage: "选择图片",
  regionFields: "区域 X/Y/宽/高",
  resultMetadata: "结果信息",
  ocrRegion: "识别选区",
  ocrAndTranslate: "识别并翻译",
  translateRegion: "翻译区域",
  retranslate: "重新翻译",
  copy: "复制",
  pin: "固定",
  unpin: "取消固定",
  close: "关闭",
  translationPlaceholder: "翻译结果会显示在这里。",
  sourcePlaceholder: "OCR 或划词原文会显示在这里。",
  noImageSelected: "未选择图片",
  imageLoaded: "图片已加载",
  textInputRequired: "请输入要翻译的文本",
  textTranslated: "文本已翻译",
  ocrTextExtracted: "OCR 文本已提取",
  imageTranslated: "图片已翻译",
  regionTranslated: "区域已翻译",
  selectedRegionTooSmall: "选区太小",
  noImageDimensions: "图片尺寸尚未就绪，请重新选择图片后再框选。",
  unsupportedImageType: "不支持的图片类型，请使用 PNG、JPEG 或 WebP。",
  noResultToCopy: "没有可复制的结果",
  resultCopied: "结果已复制",
  noResultToPin: "没有可固定的结果",
  resultPinned: "结果已固定",
  resultUnpinned: "已取消固定",
  resultClosed: "结果已关闭",
  interfaceLanguage: "界面语言",
  targetLanguage: "目标语言",
  theme: "主题",
  resultDock: "结果停靠",
  screenshotHotkey: "截图热键",
  selectionHotkey: "划词热键",
  validateModels: "检查 OCR Worker",
  save: "保存",
  saving: "保存中",
  saved: "已保存",
  saveSettings: "保存配置",
  saveSettingsHint: "保存后会立即更新运行中的配置，新翻译请求会使用最新设置。",
  checkPermissions: "检查权限",
  copyDiagnostics: "复制诊断",
  diagnostics: "诊断工具",
  provider: "翻译服务",
  providerSaveHint: "切换翻译源后需要保存；SnapText 免费源地址由客户端环境配置决定。",
  unsavedChanges: "有未保存更改",
  refresh: "刷新",
  clear: "清空",
  copyHistory: "复制历史",
  open: "打开",
  cancel: "取消",
  pinnedResult: "固定结果",
  pinnedResultWindow: "固定结果窗口",
  sourceType: "来源类型",
  sourceText: "原文",
  translationText: "译文",
  noResult: "暂无结果",
  noTarget: "暂无目标语言",
  sourceScreenshot: "截图",
  sourceSelection: "划词",
  sourceImage: "图片",
  sourceTextKind: "文本",
  preparingOverlay: "正在准备框选窗口",
  overlayInstruction: "拖拽选择区域，松开后翻译，按 Escape 取消。",
  noOverlayScreenshot: "暂无可用的框选截图",
  ocrSelectedRegion: "正在识别所选区域",
  translatingSelectedRegion: "正在翻译所选区域",
  translating: "正在翻译",
  overlayClosed: "框选窗口已关闭",
  modelStatusNotChecked: "尚未检查 OCR Worker",
  configurationNotValidated: "配置尚未校验",
  configSaved: "配置已保存",
  ocrModelsValidated: "OCR Worker 可用",
  ocrModelFilesMissing: "OCR Worker 不可用",
  desktopCapabilitiesChecked: "桌面能力已检查",
  noDesktopCapabilitiesToCopy: "没有可复制的桌面能力诊断",
  desktopCapabilitiesCopied: "桌面能力诊断已复制",
  historyLoaded: "历史记录已加载",
  historyCleared: "历史记录已清空",
  noHistoryTitle: "暂无历史记录",
  noHistoryDescription: "完成一次文本、截图或图片翻译后，记录会显示在这里。",
  noHistoryToCopy: "没有可复制的历史记录",
  historyCopied: "历史记录已复制",
  historyItemOpened: "已打开历史记录",
  pinnedWindowHidden: "固定窗口已隐藏",
  noSourceTextForRetranslation: "没有可重新翻译的原文",
  resultRetranslated: "结果已重新翻译",
  autoDetectLanguage: "自动识别",
  themeSystem: "跟随系统",
  themeLight: "浅色",
  themeDark: "深色",
  dockCursor: "跟随光标",
  dockFixed: "固定面板",
};

const en: Labels = {
  ...zhCN,
  ready: "Ready",
  subtitle: "Desktop OCR translation workspace",
  home: "Home",
  history: "History",
  settings: "Settings",
  workspaceTitle: "Translation workspace",
  textInput: "Text input",
  textInputPlaceholder: "Type or paste text, or fill it from a screenshot/image OCR region.",
  translateText: "Translate text",
  startOverlay: "Select screenshot area",
  captureRegion: "Capture region",
  imageInput: "Image input",
  selectImage: "Select image",
  regionFields: "Region X/Y/W/H",
  resultMetadata: "Result metadata",
  ocrRegion: "OCR region",
  ocrAndTranslate: "OCR and translate",
  translateRegion: "Translate region",
  retranslate: "Retranslate",
  copy: "Copy",
  pin: "Pin",
  unpin: "Unpin",
  close: "Close",
  translationPlaceholder: "Translation result will appear here.",
  sourcePlaceholder: "OCR or selected source text will appear here.",
  noImageSelected: "No image selected",
  imageLoaded: "Image loaded",
  textInputRequired: "Enter text to translate",
  textTranslated: "Text translated",
  ocrSelectedRegion: "Recognizing selected area",
  translatingSelectedRegion: "Translating selected area",
  translating: "Translating",
  autoDetectLanguage: "Auto-detect",
  sourceType: "Source type",
  sourceText: "Source",
  translationText: "Translation",
  saving: "Saving",
  saved: "Saved",
  saveSettings: "Save settings",
  saveSettingsHint: "Saving updates the running configuration for new translation requests.",
  diagnostics: "Diagnostics",
  providerSaveHint:
    "Save after changing the translation provider; SnapText Cloud uses the client environment setting.",
  unsavedChanges: "Unsaved changes",
  noHistoryTitle: "No history yet",
  noHistoryDescription: "Text, screenshot, and image translations will appear here after you run them.",
};

export function labelsForLanguage(language?: string): Labels {
  return language === "en" ? en : zhCN;
}
